# Generated by Django 6.0.4 on 2026-04-09 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_consumptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='store',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.groceryitem')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
