# Generated by Django 6.0.4 on 2026-04-09 09:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_groceryitem_store_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='unit',
            field=models.CharField(choices=[('portion', 'Portion'), ('grams', 'Grams (g)'), ('kilograms', 'Kilograms (kg)'), ('ounces', 'Ounces (oz)'), ('pounds', 'Pounds (lbs)'), ('milliliters', 'Milliliters (ml)'), ('liters', 'Liters (L)'), ('cups', 'Cups'), ('tablespoons', 'Tablespoons (tbsp)'), ('teaspoons', 'Teaspoons (tsp)'), ('pieces', 'Pieces')], default='portion', max_length=20),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='low_stock_threshold',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='remaining_portions',
            field=models.IntegerField(default=1, help_text='Legacy field - use quantity instead'),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='total_portions',
            field=models.IntegerField(default=1, help_text='Legacy field - use total_quantity instead'),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='inventory.groceryitem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.recipe')),
            ],
            options={
                'ordering': ['item__name'],
                'unique_together': {('recipe', 'item')},
            },
        ),
    ]
