# Generated by Django 6.0.4 on 2026-04-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_recipe_groceryitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionlog',
            name='calories',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='consumptionlog',
            name='carbs',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='consumptionlog',
            name='fat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='consumptionlog',
            name='protein',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
